version: '3.8'

services:

  teledok_api:
    build:
      context: .
      dockerfile: src/Teledok.Api/Dockerfile
    container_name: teledok_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TeledokDbContext=Server=my_postgres;Port=5432;Database=mydatabase;User Id=myuser;Password=mypassword;
    ports:
      - "5000:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: